### ISSUE TITLE
Check "Custom Properties" based on browser needs

### ISSUE THREAD

**Issue by paulobmarcos** [moxystudio/postcss-preset#31]
Custom properties are currently supported by most browsers:

![imagem](https://user-images.githubusercontent.com/11398440/64954419-6cd63500-d87d-11e9-980f-720af069c0d9.png)

Although there are a few, like IE, that do not provide support by default.

We should try and only enable custom properties based on which browsers we aim to support and their needs.

**Comment by satazor** [comment]
We are using native css vars now, closing.
